[package]
name = "transfer-program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.10.1"
solana-program = "1.15.1"
spl-token = { version = "3.5.0", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
